Update issue-creator.yml

diff --git a/.github/workflows/issue-creator.yml b/.github/workflows/issue-creator.yml
--- a/.github/workflows/issue-creator.yml
+++ b/.github/workflows/issue-creator.yml
@@ -16,8 +16,7 @@ jobs:
     runs-on: ubuntu-latest
     steps:
       - name: Fail
-        run: |
-           echo "done"
+        run: exit 1
 
   test-job:
     needs: always-fail
@@ -57,15 +56,16 @@ jobs:
     #     fi
     #   shell: bash
     
-    # - name: Get failed job
-    #   id: failed-job
-    #   run: |
-    #       for job in ${{ needs.* }}; do
-    #           if [[ "${{ needs.${job}.result }}" == "failure" ]]; then
-    #               echo "::set-output name=failed-job::$job.name"
-    #               break
-    #           fi
-    #       done
+    - name: Get failed job
+      id: failed-job
+      run: |
+          for job in ${{ needs.*. }}; do
+              # if [[ "${{ needs.${job}.result }}" == "failure" ]]; then
+              #     echo "::set-output name=failed-job::$job.name"
+              #     break
+              echo ${job}
+              fi
+          done
           
     - name: Print failed-job
       run: echo "${{ steps.failed-job.outputs.failed-job }}"
